repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        exclude: '^data/[^/]+\.csv'
      - id: mixed-line-ending
        exclude: '^data/[^/]+\.csv'
      - id: end-of-file-fixer
        exclude: '^data/[^/]+\.csv'
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        exclude: '^data/[^/]+\.csv'
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      - id: isort
        additional_dependencies: [ "toml" ]
